gitlab-server:
  {{if (.Values.ssh_port) or (.Values.http_port) or (.Values.https_port)}}ports:{{end}}
  {{if .Values.ssh_port}}- ${ssh_port}:22/tcp{{end}}
  {{if .Values.http_port}}- ${http_port}:80/tcp{{end}}
  {{if .Values.https_port}}- ${https_port}:443/tcp{{end}}
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab

